name: Compile LaTeX document
on: 
  push:
    branches:
      - main  # or the name of your default branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
    - name: Get next version
      uses: reecetech/version-increment@2023.9.3
      id: version
      with:
        scheme: semver
        increment: patch
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: main.pdf
        tag_name: v${{ steps.version.outputs.version }}