name: Compile LaTeX document
on: 
  push:
    tags:
      - 'v*'  # Trigger on any push tag starting with 'v'
    branches:
      - main  # or the name of your default branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "main.pdf"
        bodyFile: "README.md"